name: Dump

on:
  workflow_dispatch:
    inputs:
      DUMP_URL:
        description: "Direct url to a recovery zip"
        default: "https://bigota.d.miui.com/V14.0.3.0.TGCMIXM/miui_SPESGlobal_V14.0.3.0.TGCMIXM_308da77f3c_13.0.zip"

jobs:
  dump:
    runs-on: ubuntu-latest

    steps:
      - name: Cleanup
        uses: rokibhasansagar/slimhub_actions@main

      - name: Checkout
        uses: actions/checkout@v3

      - name: Environment
        run: bash setup.sh

      - name: Secrets
        run: |
          echo "${{ secrets.GIT_TOKEN }}" > .githubtoken
          echo "${{ secrets.TELEGRAM_TOKEN }}" > .tgtoken

      - name: Dumpyara
        run: bash dumpyara.sh ${{ inputs.DUMP_URL }}
